
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  DBNAME: {{ .Values.db.name }}
  DBUSER: {{ .Values.db.user }}
  DBPASSWORD: {{ .Values.db.password }}
  DBHOST:  {{ .Values.db.host  }}
  DBPORT: {{ .Values.db.port }}
  SECRET_KEY: {{ .Values.secret }}
        